### ISSUE TITLE
Directory '.' is not installable. File 'setup.py' not found.

### ISSUE THREAD

**Issue by johndpope** [wells-wei-wei/smplify-x_in_docker#1]
Directory '.' is not installable. File 'setup.py' not found.
The command '/bin/sh -c cd /home/playing_smplifyx/ && pip3 install -r requirements.txt && cd human_body_prior && pip3 install .' returned a non-zero code: 1

fyi - seeing this error.
I'll see if I can fix  
Step 23/35 : RUN cd /root/torch-mesh-isect/ && python3 setup.py install
 ---> Running in db93b7b5c2b9
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
running bdist_egg
running egg_info
creating mesh_intersection.egg-info
writing mesh_intersection.egg-info/PKG-INFO
writing dependency_links to mesh_intersection.egg-info/dependency_links.txt
writing requirements to mesh_intersection.egg-info/requires.txt
writing top-level names to mesh_intersection.egg-info/top_level.txt
writing manifest file 'mesh_intersection.egg-info/SOURCES.txt'
reading manifest file 'mesh_intersection.egg-info/SOURCES.txt'
writing manifest file 'mesh_intersection.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/mesh_intersection
copying mesh_intersection/bvh_search_tree.py -> build/lib.linux-x86_64-3.6/mesh_intersection
copying mesh_intersection/__init__.py -> build/lib.linux-x86_64-3.6/mesh_intersection
copying mesh_intersection/loss.py -> build/lib.linux-x86_64-3.6/mesh_intersection
copying mesh_intersection/filter_faces.py -> build/lib.linux-x86_64-3.6/mesh_intersection
running build_ext
building 'bvh_cuda' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/root/torch-mesh-isect/include -I/root/torch-mesh-isect/inc/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c src/bvh.cpp -o build/temp.linux-x86_64-3.6/src/bvh.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=bvh_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/root/torch-mesh-isect/include -I/root/torch-mesh-isect/inc/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c src/bvh_cuda_op.cu -o build/temp.linux-x86_64-3.6/src/bvh_cuda_op.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DPRINT_TIMINGS=0 -DDEBUG_PRINT=0 -DERROR_CHECKING=1 -DCOLLISION_ORDERING=1 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=bvh_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
src/bvh_cuda_op.cu: In lambda function:
src/bvh_cuda_op.cu:945:128: warning: 'c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)' is deprecated [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(
                                                                                                                                ^
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:47:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
 ^~~~~~~~~~~
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/bvh.o build/temp.linux-x86_64-3.6/src/bvh_cuda_op.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/bvh_cuda.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/mesh_intersection
copying build/lib.linux-x86_64-3.6/mesh_intersection/bvh_search_tree.py -> build/bdist.linux-x86_64/egg/mesh_intersection
copying build/lib.linux-x86_64-3.6/mesh_intersection/__init__.py -> build/bdist.linux-x86_64/egg/mesh_intersection
copying build/lib.linux-x86_64-3.6/mesh_intersection/loss.py -> build/bdist.linux-x86_64/egg/mesh_intersection
copying build/lib.linux-x86_64-3.6/mesh_intersection/filter_faces.py -> build/bdist.linux-x86_64/egg/mesh_intersection
copying build/lib.linux-x86_64-3.6/bvh_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/mesh_intersection/bvh_search_tree.py to bvh_search_tree.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/mesh_intersection/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/mesh_intersection/loss.py to loss.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/mesh_intersection/filter_faces.py to filter_faces.cpython-36.pyc
creating stub loader for bvh_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/bvh_cuda.py to bvh_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying mesh_intersection.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mesh_intersection.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mesh_intersection.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mesh_intersection.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mesh_intersection.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
__pycache__.bvh_cuda.cpython-36: module references __file__
creating dist
creating 'dist/mesh_intersection-0.1.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mesh_intersection-0.1.0-py3.6-linux-x86_64.egg
creating /usr/local/lib/python3.6/dist-packages/mesh_intersection-0.1.0-py3.6-linux-x86_64.egg
Extracting mesh_intersection-0.1.0-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
Adding mesh-intersection 0.1.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/mesh_intersection-0.1.0-py3.6-linux-x86_64.egg
Processing dependencies for mesh-intersection==0.1.0
Searching for torch==1.1.0
Best match: torch 1.1.0
Adding torch 1.1.0 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /usr/local/bin
Installing convert-onnx-to-caffe2 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Searching for numpy==1.18.4
Best match: numpy 1.18.4
Adding numpy 1.18.4 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.6 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for mesh-intersection==0.1.0
Removing intermediate container db93b7b5c2b9
 ---> 7263b8b46515
Step 24/35 : COPY playing_smplifyx/. /home/playing_smplifyx/
 ---> 1c1339928c3e
Step 25/35 : RUN cd /home/playing_smplifyx/ && pip3 install -r requirements.txt && cd human_body_prior && pip3 install .
 ---> Running in 7b8b313f9f88
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: torch>=1.0.1.post2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Collecting torchgeometry>=0.1.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a6/d6/3f6820c0589bc3876080c59b58a3bad11af746a7b46f364b1cde7972bd72/torchgeometry-0.1.2-py2.py3-none-any.whl (42kB)
Collecting PyYAML==5.1.1 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz (274kB)
Collecting configargparse (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/bb/79/3045743bb26ca2e44a1d317c37395462bfed82dbbd38e69a3280b63696ce/ConfigArgParse-1.2.3.tar.gz (42kB)
Collecting smplx (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/6d/c6/332bac1ceed39fe906aa71247808f810d3cb488f62ffbf78ea38ac462cde/smplx-0.1.15-py3-none-any.whl
Collecting pillow (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e0/50/8e78e6f62ffa50d6ca95c281d5a2819bef66d023ac1b723e253de5bda9c5/Pillow-7.1.2-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Collecting opencv-python (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/72/c2/e9cf54ae5b1102020ef895866a67cb2e1aef72f16dd1fde5b5fb1495ad9c/opencv_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (28.2MB)
Collecting tqdm (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/c9/40/058b12e8ba10e35f89c9b1fdfc2d4c7f8c05947df2d5eb3c7b258019fda0/tqdm-4.46.0-py2.py3-none-any.whl (63kB)
Building wheels for collected packages: PyYAML, configargparse
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
  Running setup.py bdist_wheel for configargparse: started
  Running setup.py bdist_wheel for configargparse: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/bd/d6/53/034032da9498bda2385cd50a51a289e88090b5da2d592b1fdf
Successfully built PyYAML configargparse
Installing collected packages: torchgeometry, PyYAML, configargparse, smplx, pillow, opencv-python, tqdm
Successfully installed PyYAML-5.1.1 configargparse-1.2.3 opencv-python-4.2.0.34 pillow-7.1.2 smplx-0.1.15 torchgeometry-0.1.2 tqdm-4.46.0
Directory '.' is not installable. File 'setup.py' not found.
The command '/bin/sh -c cd /home/playing_smplifyx/ && pip3 install -r requirements.txt && cd human_body_prior && pip3 install .' returned a non-zero code: 1
(jukebox) ➜  smplify-x_in_docker git:(master) asdf 
(jukebox) ➜  smplify-x_in_docker git:(master) docker build -t smplx/smplify-x:v1 .

Sending build context to Docker daemon  1.516GB
Step 1/35 : FROM nvidia/cudagl:10.0-devel-ubuntu18.04
 ---> 5f583562cdaa
Step 2/35 : COPY sources.list etc/apt
 ---> Using cache
 ---> eadbd4632133
Step 3/35 : RUN apt-get update
 ---> Using cache
 ---> e4c70b810ffe
Step 4/35 : RUN apt-get install python3 -y && apt install python3-pip -y
 ---> Using cache
 ---> cb1140495416
Step 5/35 : RUN apt-get install openssl -y && apt-get install libssl-dev -y
 ---> Using cache
 ---> cb3d019efbc3
Step 6/35 : RUN apt-get install git -y
 ---> Using cache
 ---> 12e99355e893
Step 7/35 : RUN apt-get install wget -y
 ---> Using cache
 ---> 6a39bb7b1eec
Step 8/35 : RUN apt-get install mlocate -y && updatedb
 ---> Using cache
 ---> 1aec47c07917
Step 9/35 : RUN apt-get install vim -y
 ---> Using cache
 ---> 34cc22c7dff7
Step 10/35 : COPY cmake-3.17.1/. /root/cmake/
 ---> Using cache
 ---> 40103f7811b2
Step 11/35 : RUN cd /root/cmake/ && ./bootstrap && make -j8 && make install && ln -s /usr/local/bin/cmake /usr/bin/cmake
 ---> Using cache
 ---> 55f9bef25b6b
Step 12/35 : COPY boost_1_72_0/. /root/boost/
 ---> Using cache
 ---> 34da003d9e29
Step 13/35 : RUN cd /root/boost/ && ./bootstrap.sh && ./b2 install
 ---> Using cache
 ---> 978df0f513d3
Step 14/35 : COPY opencv-4.2.0/. /root/opencv/
 ---> Using cache
 ---> 7b26a7848678
Step 15/35 : RUN cd /root/opencv/ && mkdir build && cd build && cmake .. && make -j20 && make install
 ---> Using cache
 ---> 3aea716b1273
Step 16/35 : RUN cd /root/ && wget http://file.ppwwyyxx.com/nvidia/cudnn-10.0-linux-x64-v7.6.4.38.tgz && tar -xzf cudnn-10.0-linux-x64-v7.6.4.38.tgz -C /usr/local && ldconfig
 ---> Using cache
 ---> 649d6cc93455
Step 17/35 : COPY openpose/. /root/openpose/
 ---> Using cache
 ---> 4dae48c11d2c
Step 18/35 : RUN apt-get install libprotobuf-dev protobuf-compiler -y && apt-get install libgoogle-glog-dev -y && apt-get install libhdf5-dev -y && apt-get install libatlas-base-dev -y
 ---> Using cache
 ---> 867e9433ba69
Step 19/35 : RUN cd /root/openpose/ && mkdir build && cd build && cmake -DBUILD_PYTHON=ON .. && make -j20 && cp -r python/openpose /usr/local/lib/python3.6/dist-packages/
 ---> Using cache
 ---> ee18819a3982
Step 20/35 : RUN apt-get install libsm6 libxrender1 libfontconfig1 libxext6 -y && apt-get install freeglut3-dev -y
 ---> Using cache
 ---> 27c91adf4c5a
Step 21/35 : COPY torch-mesh-isect/. /root/torch-mesh-isect/
 ---> Using cache
 ---> 4dc201894730
Step 22/35 : RUN pip3 install torch==1.1.0
 ---> Using cache
 ---> bbdf9c126924
Step 23/35 : RUN cd /root/torch-mesh-isect/ && python3 setup.py install
 ---> Using cache
 ---> 7263b8b46515
Step 24/35 : COPY playing_smplifyx/. /home/playing_smplifyx/
 ---> Using cache
 ---> 1c1339928c3e
Step 25/35 : RUN cd /home/playing_smplifyx/ && pip3 install -r requirements.txt && cd human_body_prior && pip3 install .
 ---> Running in d09ce22115aa
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: torch>=1.0.1.post2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Collecting torchgeometry>=0.1.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a6/d6/3f6820c0589bc3876080c59b58a3bad11af746a7b46f364b1cde7972bd72/torchgeometry-0.1.2-py2.py3-none-any.whl (42kB)
Collecting PyYAML==5.1.1 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz (274kB)
Collecting configargparse (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/bb/79/3045743bb26ca2e44a1d317c37395462bfed82dbbd38e69a3280b63696ce/ConfigArgParse-1.2.3.tar.gz (42kB)
Collecting smplx (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/6d/c6/332bac1ceed39fe906aa71247808f810d3cb488f62ffbf78ea38ac462cde/smplx-0.1.15-py3-none-any.whl
Collecting pillow (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e0/50/8e78e6f62ffa50d6ca95c281d5a2819bef66d023ac1b723e253de5bda9c5/Pillow-7.1.2-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Collecting opencv-python (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/72/c2/e9cf54ae5b1102020ef895866a67cb2e1aef72f16dd1fde5b5fb1495ad9c/opencv_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (28.2MB)
Collecting tqdm (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/c9/40/058b12e8ba10e35f89c9b1fdfc2d4c7f8c05947df2d5eb3c7b258019fda0/tqdm-4.46.0-py2.py3-none-any.whl (63kB)
Building wheels for collected packages: PyYAML, configargparse
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
  Running setup.py bdist_wheel for configargparse: started
  Running setup.py bdist_wheel for configargparse: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/bd/d6/53/034032da9498bda2385cd50a51a289e88090b5da2d592b1fdf
Successfully built PyYAML configargparse
Installing collected packages: torchgeometry, PyYAML, configargparse, smplx, pillow, opencv-python, tqdm
Successfully installed PyYAML-5.1.1 configargparse-1.2.3 opencv-python-4.2.0.34 pillow-7.1.2 smplx-0.1.15 torchgeometry-0.1.2 tqdm-4.46.0
Directory '.' is not installable. File 'setup.py' not found.
The command '/bin/sh -c cd /home/playing_smplifyx/ && pip3 install -r requirements.txt && cd human_body_prior && pip3 install .' returned a non-zero code: 1

**Comment by johndpope** [comment]
git clone https://github.com/wells-wei-wei/smplify-x_in_docker.git --recursive

UPDATE - 
didn't work -
I'm going to update Dockerfile 
line 42 
COPY playing_smplifyx/. /home/playing_smplifyx/
RUN pip3 install git+https://github.com/nghorbani/configer
RUN pip3 install git+https://github.com/nghorbani/human_body_prior

**Comment by wells-wei-wei** [comment]
> git clone https://github.com/wells-wei-wei/smplify-x_in_docker.git --recursive
> 
> UPDATE -
> didn't work -
> I'm going to update Dockerfile
> line 42
> COPY playing_smplifyx/. /home/playing_smplifyx/
> RUN pip3 install git+https://github.com/nghorbani/configer
> RUN pip3 install git+https://github.com/nghorbani/human_body_prior



> git clone https://github.com/wells-wei-wei/smplify-x_in_docker.git --recursive
> 
> UPDATE -
> didn't work -
> I'm going to update Dockerfile
> line 42
> COPY playing_smplifyx/. /home/playing_smplifyx/
> RUN pip3 install git+https://github.com/nghorbani/configer
> RUN pip3 install git+https://github.com/nghorbani/human_body_prior

I know what happening, thanks for pointing it out
